services:
  postgres:
    image: postgres:14.22-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Caique@123
      POSTGRES_DB: db_teste
    ports:
      - 6543:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql